exp_name: segformer_864_b4_322_cosine
outdir: ./experiments/
dataset:
  root_dir: /home/vlada/datasets/cryme2022/new
  val_size: 0.05
  test_dir: /home/vlada/datasets/cryme2022/test
  with_augs: true
  input_size: 864
  batch_size: 3
  num_workers: 16
  part: full
  augmentation: null
seed: 322
model:
  pretrain_name: nvidia/mit-b4
train:
  optimizer: AdamW
  grad_accum_steps: 4
  learning_rate: 0.0003225390027474888
  min_learning_rate: 3.22e-07
  momentum: 0.9
  weight_decay: 0.0322425360573382
  lr_schedule:
    name: cosine
    step_size: 3
    gamma: 0.322
    last_epoch: 15
  n_epoch: 1000
